spring:
  application:
    name: A-demo-project-for-a-food-finder-app

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/food-finder?authSource=admin

  elasticsearch:
    rest:
      uris: http://localhost:9200